#!/usr/bin/env awk -f

# -------------------
# source:
#   https://stackoverflow.com/a/48869665
# -------------------
# usage 1:
#   <./script> -v k=2 /path/to/list.txt
# usage 2:
#   awk -f <./script> -v k=2 /path/to/list.txt
# -------------------

BEGIN{
  srand();
  if(k=="") k=1
}

/^\s*$/ {next;}
/^#.*$/ {next;}

NR <= k {
  reservoir[NR-1] = $0;
  next;
}

{ i = int(NR * rand()) }

i < k { reservoir[i] = $0 }

END {
  for (i in reservoir) {
    print reservoir[i];
  }
}
